version: '3'
services:
  blagues-api:
    container_name: blagues-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./database.sqlite:/database.sqlite
    env_file:
      - ./.env
    ports:
      - '3001:3001'
